### ISSUE TITLE
Allow option to filter out Module:s before ModuleRegistryConfiguration kicks in?

### ISSUE THREAD

**Issue by herder** [spring-projects/spring-guice#111]
We have a library that is being migrated to use Spring instead of `Module`:s, and in order to be able to migrate gradually we try to provide a mechanism to filter out any `Module` implementations that have a corresponding Spring autoconfig and use the Spring variant instead.

This work ok for most of our implementations, but some modules initialize some static fields when the `configure()` method is called on them, which causes problems when Spring tries to do the same thing later.

So we would need to be able to filter out these modules from initialization before the Guice injector is called, but that seems difficult with the current setup.

I have tried implementing a `BeanDefinitionRegistryPostProcessor` to remove the deprecated module implementations, but unfortunately the `ModuleRegistryConfiguration` has an `@Order(Ordered.HIGHEST_PRECEDENCE)` annotation on it, so I can't make my processor filter out the modules before that class is run, which causes the `configure` method to get called however I try.

I see two ways of fixing this:

1. Setting the priority on `ModuleRegistryConfiguration` to `@Ordered.HIGHEST_PRECEDENCE + 1`, to allow other processors to run before it, or
2. Extend the processor with a filtering mechanism, so that you could define a bean that implements a filter to run on the module list before the modules are used: https://github.com/spring-projects/spring-guice/blob/69731bb179295509c9d7b3ba6fee26fcd687025b/src/main/java/org/springframework/guice/annotation/ModuleRegistryConfiguration.java#L128

Would this idea make sense, or could there be some other way to handle this that I have missed?

I'd be happy to write a PR for whatever solution you would recommend, provided you think it's a reasonable idea :)

**Comment by dsyer** [comment]
That definitely sounds useful. I believe we already support filtering going the other way (excluding beans  from Spring when constructing a Guice module). Maybe we could look for inspiration there? Maybe you already did?

**Comment by herder** [comment]
> That definitely sounds useful. I believe we already support filtering going the other way (excluding beans from Spring when constructing a Guice module). Maybe we could look for inspiration there? Maybe you already did?

I didn't see that mechanism since I came in from the other side (i.e. removing Guice from Spring), so I just changed to 'scratch my itch' with the Guice side :)

Would you prefer that we combine the approaches somehow?

**Comment by herder** [comment]
Thank you for the merge - closing this.

**Comment by caesar-ralf** [comment]
Will there be a release with this change? It has been merged for a while without a release and I am interested in this feature @dsyer

**Comment by caesar-ralf** [comment]
ping @dsyer

**Comment by dsyer** [comment]
Thanks for the reminder. Should be in Maven Central shortly.
