### ISSUE TITLE
Injector gives NullPointerException when used in ApplicationConfiguration class

### ISSUE THREAD

**Issue by kushalsethi** [spring-projects/spring-guice#116]
Created a configuration class as below.
But, injector is not initialised and giving NullPointerException when trying to get Service instance. `Service` is defined in guice library.

```
@Configuration
@EnableGuiceModules
public class AGGuiceSpringConfig {

    @Autowired
    private Injector injector;

    @Bean
    public Service service() {
        return injector.getInstance(Service.class);
    }

}
```

Could someone @dsyer @trevormarshall  please guide if I have missed on anything?

**Comment by dsyer** [comment]
You would have to provide a sample application to show how this happens. It looks pretty standard.

**Comment by kushalsethi** [comment]
Thanks
