### ISSUE TITLE
SpringModule does not accept dependencies from wrapping Injector

### ISSUE THREAD

**Issue by twicksell** [spring-projects/spring-guice#12]
SpringModule's ApplicationContext is unaware of the dependencies available in the wrapping Injector. Normally, when installing a Module, the bindings provided there could Inject bindings defined in other Modules installed in the Injector. 

Currently, its ApplicationContext is refreshed much earlier than Guice's similar lifecycle phase, so it doesn't seem possible to implement this under the current contract. I propose modifying SpringModule's construct to instead of taking a fully created ApplicationContext, take a list of @Configuration classes or base package names (mirroring AnnotationConfigApplicationContext). This would allow us to register an AutowireCandidateResolver to properly link Spring and Guice.

Pull request to follow with an initial stab at this implementation. 

@dsyer I see you've added GuiceAutowireCandidateResolver, but wasn't sure of its intent. It seems incomplete and unused. Was this something you were experimenting with?

**Comment by dsyer** [comment]
Yeah, that was an experiment. If you can do a better job, have at it.

**Comment by dsyer** [comment]
What if we turn the question round a bit. Instead of creating the `Injector` using static convenience methods in `Guice`, you could pull one out of the Spring application context. Thus, in your new test, you would replace this:

```java
        Injector injector = Guice.createInjector(new SimpleGuiceModule(),
                new SpringModule(GuiceProjectWithSpringLibraryTestSpringConfig.class));
```

with this

```java
		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
		context.register(GuiceProjectWithSpringLibraryTestSpringConfig.class, SimpleGuiceModule.class);
		context.refresh();
		Injector injector = context.getBean(Injector.class);
```

The Spring context can then be created however you like (including with Spring Boot if necessary) and it can take advantage of any existing Guice modules if you use the existing `@EnableGuiceModules` feature. You end up with the same functionality from a user API point of view, but we don't have to teach `SpringModule` any new tricks.

**Comment by dsyer** [comment]
You can even do it in one line with Spring Boot

```java
Injector injector = new SpringInjector(SpringApplication.run(new Object[] {GuiceProjectWithSpringLibraryTestSpringConfig.class, SimpleGuiceModule.class}, new String[]));
```

**Comment by dsyer** [comment]
(I added your test to master in 5708ba0 with the change above.)

**Comment by twicksell** [comment]
Thats a handy way of doing it if you control (or are willing to change) the creation of the Injector, but unfortunately thats not what I'm dealing with at the moment. Over here we have a large number of existing Guice based apps, already creating an Injector (not even Guice, but Governator, so already wrapped). In those Applications we have several libraries being crafted by different teams, some of which have moved towards writing code using Spring instead of Guice. So they have Spring configs ready to be consumed. An Injector-based app owner now wants to consume that code. In a pure Guice setting the natural thing to do would be to install a Module and nothing else. 

If you think of it from a Spring-centric view, the natural thing to do would be to @Import a Config, or perhaps @Enable<SomeFeature>. And instead, we'd be asking them to build their application context in a different way.

**Comment by dsyer** [comment]
Well, from a Spring point of view you can actually `@Import` a Guice module. So maybe it would be better to fix Govenator?

Or we can take yet another perspective then, and ask why this fails:

```java
Injector injector = Guice.createInjector(new SpringModule(context));
```

If that would work, you could create the Spring context first and pass it into your favourite convenience method.

**Comment by twicksell** [comment]
`new SpringModule(context)` fails because everything in that context is eagerly instantiated. If a dependency is missing (that would've otherwise been provided by the Injector in which you're installing the SpringModule) your context will fail to be created with a `NoSuchBeanDefinitionException`. The user could create the context in a mode that doesn't auto-refresh, set the `AutowireCandidateResolver` yourself, and then refresh. But that seemed a bit complex to expose to the user in documentation.

**Comment by dsyer** [comment]
That wasn't what I meant (the code I posted blows up independent of how you create the Spring context). I was just showing that there are things going on in Guice that I don't understand.

Maybe we can move forward if you can describe your use case in more detail? How come you can't pull all the modules that you need into a Spring context, before creating an `Injector`? I assume it must be an implementation detail of Governator, because I can't see anything in the Guice API that prevents you from doing that.

**Comment by twicksell** [comment]
Ah, sorry I missed that. No, its not a Governator or Guice thing, just a practicality that we keep running into when working with applications that are already written in Guice.

In your version of the test, you've created a situation where all dependencies are defined in Spring, constructed in Spring, and then presented back as an Injector. But the heart of the test for me is the ability to have some dependencies defined in Guice, some in Spring, and the having the two bridged in a reasonable fashion. This means users of Spring-provided bindings shouldn't have to rewrite their application in any major way when consuming Spring configs. In fact, if we could get away with refactoring everything into an ApplicationContext we wouldn't need Spring-Guice at all, we'd just fully migrate to Spring. Our goal in using Spring-Guice is to ease that migration such that it doesn't need to take place all at once. 

For a more detailed use case, lets say you have a Guice application, and you want to consume to functionality from a Spring-based library. That library may depend on some infrastructure bean, say `AWSCredentialsProvider`. The library knows it needs one, but doesn't care what implementation, so it simply `@Injects` it. My existing Guice application already has a binding for `AWSCredentialsProvider` defined somewhere, as its a common dependency. In a reasonably complex application, this situation will repeat itself dozens of times. 

In a pure Guice world, this is no problem as bindings defined in Modules have their dependencies resolved against all bindings in the injector. Just as in Spring when you do an `@Import(SomeConfig.class)` beans have their dependencies resolved against everything available in the appContext. When using both Spring & Guice together, I want both the appContext and the Injector to be a part of resolving dependencies. So my PR does a best effort at tying the two processes together, and also gives SpringModule what I think is a more appropriate contract for this purpose. Just like `@Import(SomeConfig.class)`, all it asks for is config classes, not a fully constructed appContext. Nothing is instantiated until the Injector goes through its equivalent of an appContext refresh. The dependency graph has already been worked out and fails fast if something can't be resolved. This may be something of a change from how SpringModule was originally intended to be used, so I'm happy to subclass my implementation into something more specific.

**Comment by dsyer** [comment]
So in your example, what is the contract of the Spring library? What does it provide? I assume it has classes that implement a feature that it wants to share with other (non-Spring) apps, and it expresses that as a public class with `@Inject` points. What does it get from Spring in that case? If it knows it is going to be consumed by Guice it could provide a `Module` I guess. Is that what you want to avoid? So maybe it wants to express itself through a `@Configuration` class and doesn't want to know that Guice users depend on it?

Would it be a good idea to provide Guice users with a generic way to create an additional configuration that can bridge to Guice, so it can be added to a Spring context containing the library feature but only resolve dependencies lazily?  Example:

```java
Injector injector = Guice.createInjector(new SimpleGuiceModule(),
                new SpringModule(GuiceProjectWithSpringLibraryTestSpringConfig.class, GenericGuiceDependencies.class));
```

(P.S. that code will still crash because of the mysterious Guice internal error that I mentioned above - so we'd need to work out what that is and how to get rid of it as well.)

The main thing I want to avoid is baking any kind of logic for creating an `ApplicationContext` into Spring Guice. That logic is much better implemented by users using Spring Boot.

Maybe a concrete example with actual code, even if it is not "real", would be the way forward here?

**Comment by twicksell** [comment]
>If it knows it is going to be consumed by Guice it could provide a Module I guess. Is that what you want to avoid?

Yes.
> So maybe it wants to express itself through a `@Configuration` class and doesn't want to know that Guice users depend on it?

This is the case. We have factions of developers both writing pure Spring and pure Guice. They're sharing code on how to communicate between their apps by writing "client libraries", not in the sense of utility functions like Guava, but in the sense of providing some kind of business logic and making assumptions about what dependencies will be available to them. That library may expect things like `AWSCredentialsProvider`or `EurekaClient` to already be available in the AppContext. A poor contract to be sure, but a fairly common one from my experience. We don't want to mandate everyone use exclusively Spring or Guice (because that would mean we'd be forever stuck with Guice :( ) So we want to let people write both their Applications and their client libraries using the DI framework they are familiar with. And because not everyone is willing to write their library twice for the benefit of others on a different DI framework, we want Spring-Guice to step in and help blend the two approaches. 

> Would it be a good idea to provide Guice users with a generic way to create an additional configuration that can bridge to Guice, so it can be added to a Spring context containing the library feature but only resolve dependencies lazily? Example:

That is what my PR is attempting to do really. The example you provided is just about the same as my test case. But without changing SpringModule as I did, how in your example would the user plumb a Provider<Injector> through Config classes and back into something like an AutowireCandidateResolver to actually allow for the resolution of dependencies from the Injector? I couldn't figure out any reasonable way of doing that without dumping the reference to the Provider<Injector> into a static variable (bad for testing) or some ThreadLocal (bad for my own personal sanity). 

>The main thing I want to avoid is baking any kind of logic for creating an ApplicationContext into Spring Guice. That logic is much better implemented by users using Spring Boot.

The reason for creating an ApplicationContext is because its the most expedient way to parse/understand a collection of Spring config's appropriately. I think how that ApplicationContext is build is an implementation detail of the SpringModule which isn't really relevant to the user.  Typically, any configuration they might want to do of that AppContext is doable via the many hooks and postprocessors in Spring. However, if we really want to allow full control for the user to handle app context creation, we could always provide some kind of factory interface. This is what I did for `@EnableGuiceModules` in the opposite direction to allow for the user to control Injector creation. Something like:
```
public interface ApplicationContextFactory {
      //BeanFactory here would already be pre-populated with our GuiceAutowireCandidateResolver
      //with the proper reference to Provider<Injector> passed by SpringModule.
      public ApplicationContext getApplicationContextForBeanFactory(BeanFactory bf);
}

...
//usage of optional constructor in SpringModule which takes ApplicationContextFactory
new SpringModule((bf) -> /*build your context however you like, provided you pass in our bean factory*/);
...
```
My only problem with the above is that if they don't use the provided BeanFactory there won't be any good way of messaging them about why they will be getting NoSuchBeanDefinitionFound errors for Guice-provided dependencies. 

> Maybe a concrete example with actual code, even if it is not "real", would be the way forward here?
What would be helpful, a sample application? I'm also happy to hop onto Skype or Slack if that would make things easier. 

This might sound like something of a strange usecase, but I really appreciate your help in working through this.

**Comment by dsyer** [comment]
> I'm also happy to hop onto Skype or Slack if that would make things easier. 

Not necessary (and it's nearly the weekend here anyway). If you could push a simple sample app + with a library to github that would help me get up to speed when I get back to it.

**Comment by twicksell** [comment]
Quick and dirty example > https://github.com/twicksell/spring-guice-failing-example 
This fails with the current implementation, but passes with my PR. Run the main method in the "Main" class.

**Comment by dsyer** [comment]
OK, so I merged the PR (490fc20) and extracted the code that creates a bean factory out into a `BeanFactoryProvider` convenience class. That way the `SpringModule` doesn't change its contract (except for picking up a new constructor).

There's a TODO in there about how to close the `ApplicationContext` if you have any bright ideas (Guice doesn't really have an end of life callback, does it?).

**Comment by twicksell** [comment]
Thanks! 

> There's a TODO in there about how to close the ApplicationContext if you have any bright ideas (Guice doesn't really have an end of life callback, does it?).

No, Guice has no lifecycle management. I think the best compromise is to add a binding  either to the ApplicationContext, or preferrably some new interface we create that wraps the ApplicationContext and allows the user to close it manually. SpringGuiceContextManager.close() or something like that. That would at least give people who've implemented a Lifecycle feature on top of Guice a way to clean up the context. Governator, for example, automatically closes all bindings which implement Closeable.

**Comment by dsyer** [comment]
OK, thanks for the info. There's a 1.0.0.M1 if you want a stable build (I mainly did that to test the CI pipeline, but it might be a useful side effect for you). Let me know if it's working.

**Comment by twicksell** [comment]
👍 Works like a charm, thanks!
