### ISSUE TITLE
NullPointerException in SpringModule when using Spring Boot JPA 

### ISSUE THREAD

**Issue by twicksell** [spring-projects/spring-guice#18]
Something interesting about the following bean definition:

```
Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=true; factoryBeanName=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration; factoryMethodName=entityManagerFactory; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]
```
This results in an NPE at https://github.com/spring-projects/spring-guice/blob/master/src/main/java/org/springframework/guice/module/SpringModule.java#L105 because `beanFactory.getType(name)` returns null for that particular definition. 

Not sure if the best course of action is a simple null check, or if there is some smarter way to check for this type of definition.

**Comment by dsyer** [comment]
Fixed in #19
