### ISSUE TITLE
GuiceModuleMetatdata throws java.io.FileNotFoundException on parameterized types

### ISSUE THREAD

**Issue by twicksell** [spring-projects/spring-guice#20]
GuiceModuleMetadata throws java.io.FileNotFoundException when it encounters a parameterized type. It is currently just using Type.getTypeName() which includes the type information, and so it later fails when `org.springframework.core.type.classreading.SimpleMetadataReader` attempts to find the class by name.

**Comment by twicksell** [comment]
@dsyer hey Dave, mind giving this a look when you get a chance?

**Comment by dsyer** [comment]
Fixed via #21
