### ISSUE TITLE
Usage for the case of "using existing guice modules in spring application context"

### ISSUE THREAD

**Issue by elevenfang** [spring-projects/spring-guice#22]
From your example of using existing Guice Modules in a Spring ApplicationContext
```
@EnableGuiceModules
@Configuration
public static class TestConfig extends AbstractModule {

    @Bean
    public MyModule myModule() {
        return new MyModule();
    }

    @Bean
    public Spam spam(Service service) {
        return new Spam(service);
    }

}
``` 

1. Here I think no need to extend AbstractModule.

2. When we inject the service which is defined in MyModule, use inject annotation would get null while autowired would be fine.(A little confused on when use inject and when use autowired after integration spring and guice)

```
@Inject 
private Service service;
```

```
@Autowired
private Service service;
```

**Comment by dsyer** [comment]
1. Correct (I fixed the README).

2. Don't know. `@Inject` is always a synonym for `@Autowired` isn't it?
