### ISSUE TITLE
"No primary bean definition for type" exception when Using @Transactional and @EnableTransactionManagement annotations

### ISSUE THREAD

**Issue by YounesRahimi** [spring-projects/spring-guice#23]
I'm using Kotlin 1.1.4-3 and Guice and Spring Data JPA 2.0.0.RELEASE in a Play Framework (Java version) project. Play Framework version is 2.5.8.

I used [spring-projects/spring-guice](https://github.com/spring-projects/spring-guice#registering-spring-configuration-classes-as-a-guice-module) library and specifically the method which is named **Registering Spring Configuration Classes as a Guice Module** to integrate Spring and Guice as DI library for Play Framework.

I declared an interface as a base for a Spring service. The syntaxes are in Kotlin language.

    interface PersonPresenceManagement {
        
        fun autoGenerateOrUpdatePersonPresences(companyInfo: CompanyInfo)
        fun generatePersonPresence(currentUser: SalaryUser, userId: Long, logPeriodId: Long): Result
        fun saveOrUpdateDailyReport(currentUser: SalaryUser, personPresenceDbId: Long, dailyReport: DailyReport): Result
    }

As mentioned in the [Spring Data JPA documentation](https://github.com/spring-projects/spring-data-jpa/blob/master/src/main/asciidoc/jpa.adoc#transactionality):

> Another possibility to alter transactional behaviour is using a facade or service implementation that typically covers more than one repository. Its purpose is to define transactional boundaries for non-CRUD operations:

I implemented `PersonPresenceManagement` interface:

    @Service
    open class PersonPresenceManagementImpl @Inject constructor(...) : PersonPresenceManagement {
        @Transactional
        override fun generatePersonPresence(currentUser: SalaryUser, userId: Long, logPeriodId: Long): Result { ...  }

        @Transactional
        override fun autoGenerateOrUpdatePersonPresences(companyInfo: CompanyInfo) { ...  }

        @Transactional
        override fun saveOrUpdateDailyReport(currentUser: SalaryUser, personPresenceDbId: Long, dailyReport: DailyReport): Result { ... }

    }

But when running app, it throws this error:

    org.springframework.beans.BeanInstantiationException: Failed to instantiate [ir.iais.playCommons.security.handlers.GlobalDeadboltHandler]: Constructor threw exception; nested exception is com.google.inject.ProvisionException: Unable to provision, see the following errors:

    Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

    1) No primary bean definition for type: class ir.iais.salary.services.impl.PersonPresenceManagementImpl
      at spring-guice (via modules: com.google.inject.util.Modules$OverrideModule -> ir.iais.playCommons.settings.SpringDataJpaModule)
      while locating ir.iais.salary.services.PersonPresenceManagement
        for parameter 10 at controllers.PersonPresenceCtrl.<init>(PersonPresenceCtrl.kt:37)
      while locating controllers.PersonPresenceCtrl
        for parameter 6 at router.Routes.<init>(Routes.scala:112)
      while locating router.Routes
      while locating play.api.inject.RoutesProvider
      while locating play.api.routing.Router
        for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200)
      while locating play.api.http.JavaCompatibleHttpRequestHandler
      while locating play.api.http.HttpRequestHandler
        for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:221)
      at play.api.DefaultApplication.class(Application.scala:221)
      while locating play.api.DefaultApplication
      while locating play.api.Application
        for parameter 0 at play.DefaultApplication.<init>(DefaultApplication.java:30)
      at play.DefaultApplication.class(DefaultApplication.java:30)
      while locating play.DefaultApplication
      while locating play.Application
        for parameter 1 at be.objectify.deadbolt.java.ExecutionContextProvider.<init>(ExecutionContextProvider.java:40)
      at be.objectify.deadbolt.java.DeadboltModule.executionContextProvider(DeadboltModule.java:55):
    Binding(class be.objectify.deadbolt.java.ExecutionContextProvider to self in interface javax.inject.Singleton) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
      while locating be.objectify.deadbolt.java.ExecutionContextProvider

    1 error
            at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
            at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
            at org.springframework.guice.module.GuiceAutowireCandidateResolver$1.getTarget(GuiceAutowireCandidateResolver.java:81)
            at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
            at be.objectify.deadbolt.java.ExecutionContextProvider$$EnhancerBySpringCGLIB$$3cfcfcc2.get(<generated>)
            at be.objectify.deadbolt.java.AbstractDeadboltHandler.<init>(AbstractDeadboltHandler.java:42)
            at ir.iais.playCommons.security.handlers.GlobalDeadboltHandler.<init>(GlobalDeadboltHandler.kt:21)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

I even put `@Primary` annotation above `PersonPresenceManagementImpl` class but it didn't work.

I found this exception will disappear if I remove the  `@EnableTransactionManagement` annotation from my `@Configuration` class or remove the `@Transactional` annotation from `PersonPresenceManagementImpl` methods. It seems There is a bug when enabling transaction management in spring configuration.

I need to use transaction management in conjunction with spring-guice integration in our project.

StackOverflow link: [Spring Data JPA + Guice Error: No primary bean definition for type when using @EnableTransactionManagement annotation](https://stackoverflow.com/questions/46565962/spring-data-jpa-guice-error-no-primary-bean-definition-for-type-when-using-e)

Thanks.

**Comment by dsyer** [comment]
How about if you use `@EnableTransactionManagement(proxyTargetClass=true)`?

**Comment by dsyer** [comment]
N.B. the OP in #9 says he had `@Transactional` working in Play. So it probably does work if you do what I suggested.
