### ISSUE TITLE
Way to close the applicationContext 

### ISSUE THREAD

**Issue by archie-sh** [spring-projects/spring-guice#3]
Hi, I am using the play Framework which performs auto-reloads and has guice integrated in it. I got spring data beans that have a datasource i.e. Elasticsearch but no way to shut down the applicationContext between reloads which leads to a memory leak.

**Comment by FrEaKmAn** [comment]
Which version of Play are you using? If 2.4, then you can close it with adding ApplicationLifecycle https://www.playframework.com/documentation/2.4.x/JavaDependencyInjection#Stopping/cleaning-up
