### ISSUE TITLE
PrivateModule not working since 1.1.1

### ISSUE THREAD

**Issue by sblommers** [spring-projects/spring-guice#32]
I was using private modules with 1.1.0 and now with 1.1.1 i get this error.

 ```
It was already configured on one or more child injectors or private modules
    (bound by a just-in-time binding)
  If it was in a PrivateModule, did you forget to expose the binding?
  while locating 
1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1045) ~[guice-4.1.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004) ~[guice-4.1.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054) ~[guice-4.1.0.jar:na]
	at org.springframework.guice.module.GuiceAutowireCandidateResolver$1.getTarget(GuiceAutowireCandidateResolver.java:81) ~[spring-guice-1.1.1.RELEASE.jar:na]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at
```
I tried annotating them or using `@Named` instead of a custom annotation class but I had to expose my bindings without annotations (free-for-all) to make it work again.

Are there plans to allow Private Guice Modules and using them with `@Named` and `@Custom` ?
Should I rollback to 1.1.0 ?

Thanks for this project!

**Comment by dsyer** [comment]
@twicksell thinks he might have fixed it in his latest PR. Try a snapshot when the build goes green.

**Comment by sblommers** [comment]
I tested with latest snapshot and have the same end result, I have to expose the bindings without annotations to make it work now. I can live with this limitation but was wondering the difference between 1.1.0 and 1.1.1 in this case.

**Comment by twicksell** [comment]
I've written a short test for PrivateModules and it looks like they're not being picked up at all in this current version. We recently switched to using an ElementVisitor to detect bindings, and I completely missed the steps for handling private elements. I can work on re-adding that functionality, but at the moment I'm still unable to fully reproduce the issue you're describing. 

If you could provide a test case reproducing exactly the duplicate bind issue you see that'd be really helpful.

**Comment by sblommers** [comment]
it reads as if it has a duplicate but it is the normal error when guice cannot find it's binding due to wrong annotation/expose usage, it just says it cannot find the binding with or without the correct annotation on the @inject or @autowire.

**Comment by twicksell** [comment]
@sblommers would you mind having a look at https://github.com/spring-projects/spring-guice/pull/33 and seeing if there is anything about my test case that might be missing or different from yours?

**Comment by sblommers** [comment]
You are fast! The test seems to cover my case as well. Thank you for fixing this!

**Comment by sblommers** [comment]
@twicksell @dsyer is release 1.1.2 artifact going to be available on spring.io repos?

**Comment by dsyer** [comment]
It's syncing to Maven Central now (I forgot to press the button).

**Comment by sblommers** [comment]
Thanks ;-)
