### ISSUE TITLE
Support for latest Spring release version 4.2.0

### ISSUE THREAD

**Issue by RaviH** [spring-projects/spring-guice#4]
I love your work and I am using it at my work. Finally I can use Spring Modules!!!

I was wondering if I could ask you for a favor and see if you would be able to support latest Spring 4.2.0 version? I notice the code is configured to use 4.0.3.RELEASE.

That would be a huge help!

**Comment by dsyer** [comment]
It looks like there are test failures if we update to Spring 4.2. Need to check what is happening.

**Comment by RaviH** [comment]
Thank you Dave!

**Comment by pizeta74** [comment]
Tests work fine up to Spring 4.0.6.
From Spring 4.0.7 it seems something has changed to DI engine in Spring.

**Comment by dsyer** [comment]
Fixed in 72cf525

**Comment by RaviH** [comment]
Hey Dave, noticed that the bug is closed. Thank you for fixing it. What's the release version this code is fixed under?

Thanks again!

**Comment by dsyer** [comment]
AFAIK there hasn't been a release of this project yet. If you are using it and find that it works, that will be useful feedback when we are trying to decide on the roadmap.

**Comment by RaviH** [comment]
I am using it. However since it doesn't have a release we had to fork/clone it and create an internal release. Having a release and roadmap would be a great addition.

Thank you for your work!
