### ISSUE TITLE
Duplicated module's configure call

### ISSUE THREAD

**Issue by sanitas2** [spring-projects/spring-guice#49]
I am having some doubts about spring-guice running with spring boot 2.1.2. I think my use case is quite basic - I want to autowire some classes from guice module and use them in spring application. To do so I created:

```
@EnableGuiceModules
@SpringBootApplication
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
	@Bean
	public MyModule myModule() {
		return new MyModule();
	}
}
```

That allows me to inject module's services in spring application. The issue I am experiencing is that logs show that module's configure method is called twice. I assume it shouldn't happen this way. Can you tell me what might be the issue?

**Comment by twicksell** [comment]
We use Guice's ElementVisitor API which will invoke the configure method. It'll also be invoked by the injector itself when Spring Guice is initialized. This usually shouldn't be a problem. The suggestion from Guice is that modules should be "fast and side-effect free" (https://github.com/google/guice/wiki/ModulesShouldBeFastAndSideEffectFree). 

If you have some logic inside of your module that can only even be executed once, I'd suggest refactoring it into some bound class in Guice if possible.

**Comment by sanitas2** [comment]
Thank you for clearing this up and for quick response. 

I don't have such side logic, it just seemed suspicious to see those calls duplicated. If that's expected I am fine with that (I was worried I did some mistake). Anyway, I would consider mentioning this behavior in readme. Thanks.
