### ISSUE TITLE
Guice and Actuator:  No implementation for Map<String, CacheManager> was bound

### ISSUE THREAD

**Issue by primoze** [spring-projects/spring-guice#67]
Hi.
I have an issue using actuator and spring-guice. If actuator is in the dependencies I get 'WebServerException: Unable to start embedded Tomcat'. If I remove the actuator dependency it works fine. If I remove spring-guice it also works fine.

The specific guice exception is `1) No implementation for java.util.Map<java.lang.String, org.springframework.cache.CacheManager> was bound.
  while locating java.util.Map<java.lang.String, org.springframework.cache.CacheManager>`

My minimal reproducible example is as follows (I have omitted pom.xml, I'm using spring-boot 2.1.6.RELEASE and spring-guice 1.1.3.RELEASE):

Application.java defines the module and my contrived class to be injected in ExampleRest.
```
// ... snip

@SpringBootApplication
@EnableGuiceModules
public class Application {

    public static void main(String[] args) {
        SpringApplication app = new SpringApplication(
                Application.class);
        app.run(args);
    }

    @Bean
    public MyModule myModule() {
        return new MyModule();
    }
}

class MyModule implements Module {

    @Override
    public void configure(Binder binder) {
        binder.bind(PingSettings.class).toInstance(new PingSettings("pong"));
    }
}

class PingSettings {

    private final String response;

    public PingSettings(String response) {
        this.response = response;
    }

    public final String getPingResponse() {
        return response;
    }
}
```
ExampleRest.java
```
// ... snip

@RestController
public class ExampleRest {

    private final PingSettings settings;

    @Autowired
    public ExampleRest(PingSettings settings) {
        this.settings = settings;
    }

    @RequestMapping(value = "/ping", produces = "application/json", method = RequestMethod.GET)
    public String ping() {
        return settings.getPingResponse();
    }
}
```
The full exception stack trace is here: [actuator.log](https://github.com/spring-projects/spring-guice/files/3641662/actuator.log)

Not sure if its a spring-guice or actuator issue, but I'm posting here because people here will know better than me.

**Comment by dsyer** [comment]
Interesting. It works for me with Spring Boot 2.2, probably because the cache actuator is disabled by default. Maybe you could disable it in 2.1 as well as a workaround (but obviously upgrade is a good idea as well)?

**Comment by dsyer** [comment]
Actually, it also works for me with Spring Guice 1.1.14 snapshots, so I expect one of the other fixes has resolved this issue as well. I'm just waiting for @twicksell to ask for a release.

**Comment by primoze** [comment]
@dsyer Thanks, I'll give it a shot.

**Comment by saturnism** [comment]
hiya @dsyer ! what's the timeline for 1.1.4 release? i have a project which ran into the same issue. thnx!

**Comment by twicksell** [comment]
@dsyer we've tested all of the major changes on our end. I think a release is safe whenever you're ready.

**Comment by dsyer** [comment]
I have it staged to Central. Do you want #76 to be fixed?

**Comment by twicksell** [comment]
Yes, good catch. That one has been running for a little while now and did fix an issue. Its been merged.

**Comment by dsyer** [comment]
Ok. That’s done. Syncing to Central now.

**Comment by saturnism** [comment]
thanks! :D
