### ISSUE TITLE
Update dependendencies and release 2.0.0

### ISSUE THREAD

**Issue by richwxd** [spring-projects/spring-guice#87]
Only dependentbot update the dependencies. But actually both guide and spring are outdated. The project cannot work well nowadays. Maybe developers can fork them maintain separately.

**Comment by dsyer** [comment]
I'm not sure it matters about the Spring dependency. If we want a version that compiles and depends on Guice 5.x we would probably need to go to 2.0.0 with this project. I don't have any objection to that, but it would be good to hear some more opinions. There used to be a group at Netflix that was motivated to contribute to this project, but I'm not sure if they need it any more.

**Comment by simondemartini** [comment]
I think an update bumping Guice and Spring would be worthwhile. 

Since the upcoming Spring 6 release will require Java 17, we should prep for that by upgrading to Guice 5.1.0+, since that's the first version of Guice that supports 17

**Comment by richwxd** [comment]
Is there a new smart gradle way to solve the version issue? In maven, the "dependency version" is a bit complex and boring.

**Comment by dsyer** [comment]
What is the "version issue"? I'm not sure what you are getting at.

**Comment by richwxd** [comment]
It is just my feel when using spring-boot for multi-modules project. Maybe make spring-guice keeping up with spring-boot version is a good way. Otherwise when use this spring-guice, we must exclude old spring, mannually add new spring. Another point, we need some more examples to understand spring-guice deep.

**Comment by simondemartini** [comment]
Looks like someone has started a PR to get it up to Guice 5.0.1 a few months ago. Should be fairly straightforward to bump that to 5.1.0

https://github.com/spring-projects/spring-guice/pull/89

If the original author isn't around anymore I can try to take a stab at it some time

**Comment by simondemartini** [comment]
Created https://github.com/spring-projects/spring-guice/issues/91

**Comment by simondemartini** [comment]
@dsyer I created I couple PRs for the upgrades. Would you be able to take a look at those?

And if those are merged, what would the process be to get those released? Would we want to include anything else?

**Comment by dsyer** [comment]
The release process should be easy (automatic) if we can decide on a feature set and version number. The big question is compatibility with Guice and Spring versions. I will have a look through the issue list and see if anything else seems important (but my inclination is to just release something). Other opinions are welcome.

**Comment by dsyer** [comment]
One option since the version of Spring doesn't have any impact on tests (it works from 5.1 to 5.3 anyway) would be to simply make the Spring dependency optional. Users could then match spring-guice with any version they like (including the latest Spring Boot) and it should just work.

**Comment by simondemartini** [comment]
Yeah I could be on board with making Spring optional, we've actually been running spring-guice 1.x with Spring 5.3 and Guice 4.x for a while without issues. But it's also easy enough to override the spring version anyway 🤷 

I'm ok just releasing what we have for 2.0.0, but I can take a look at the issue list today too if you'd like help

**Comment by simondemartini** [comment]
Ended up creating #97 and some PRs for that if we want to include those in 2.0.0 while we're in here. Unless someone else has some stuff to get in before we release, then I'd vote for just getting 2.0.0 out sooner than later too.

Happy to help verify or contribute anything too

**Comment by dsyer** [comment]
I'm readyish for a release. In addition to the decision on making Spring an optional dependency, I'd like to circle back on #75. I remember having some conversations about it with Taylor a long time ago and slightly reluctantly realizing we might not be able to fix it - it's a bit like some other Spring annotations in that they inevitably lead to early initialization of `@Configuration` classes. But it would be good to know for sure, and document the limitation if we don't think we can avoid it.
